-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 26, 2021 at 01:45 PM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.1.32

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `btao`
--

-- --------------------------------------------------------

--
-- Table structure for table `whyweneedtostudy`
--

CREATE TABLE `whyweneedtostudy` (
  `subject` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `uploadedby` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `dateofupload` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT current_timestamp(),
  `matter` longtext COLLATE utf8_unicode_ci NOT NULL,
  `branch` varchar(20) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `whyweneedtostudy`
--

INSERT INTO `whyweneedtostudy` (`subject`, `uploadedby`, `dateofupload`, `matter`, `branch`) VALUES
('Physics', 'btao', '2019-12-10 23:55:28', 'Every Engineering student should have the question mark that As a Technical student<br>why I need to study physics, In order to understand this one let us take a simple example How the CPU is made<br>The processor is nothing but Trillions of Transistor are going to form the processor. In fact, Transistors are made from semiconductors...<br>So these are going to study briefly in physics. This Example we understood that Why we need to study physics as a computer science student', 'allbranches'),
('C Programming', 'btao', '2019-12-10 23:57:29', 'As a computer science student, it is mandatory to learn a programming language, we have so many programming languages like C, C++, JAVA, FORTRAN, PYTHON. Among them C is the first High language which is a human friend language. So Most of the people Prefer C language as a primary language', 'allbranches'),
('English', 'bt@0@dm!n', '2020-04-03 05:18:43', 'Learning English is important and people all over the world decide to study it as a second language... Knowing English increases your chances of getting a good job in a multinational company within your home country or of finding work abroad. English is the official language of 53 countries.', 'allbranches'),
('Environmental Studies', 'bt@0@dm!n', '2020-04-03 05:29:03', 'Environmental science today covers, how living and nonliving things interact. Environmental science is important to save our world from destruction. Because of mans abusive actions, the environment is not safe anymore. To sum up, the objectives of environmental studies are to develop a world in which persons are aware of and concerned about the environment and the problems associated with it, and committed to working individually as well as collectively towards solutions of current problems and prevention of future problems.', 'allbranches'),
('Engineering Drawing', 'bt@0@dm!n', '2020-04-03 06:26:09', 'The World We live in is Multidisciplinary, Academically we need to study different subjects, We Required Engineering Drawing to design anything. It is a Graphical Language that communicates ideas and information. This helps us to improve the imagination and new invention can be developed. Art without engineering is dreaming. Engineering WIthout are is Calculation...', 'allbranches'),
('M-1', 'bt@0@dm!n', '2020-04-03 06:26:50', 'Mathematics is a branch of science, which deals with numbers and their operations. It involves calculation, computation, solving of problems, etc. Its dictionary meaning states that Mathematics is the science of numbers and space or Mathematics is the science of measurement, quantity, and magnitude It is exact, precise, systematic and a logical subject.', 'allbranches'),
('Chemistry', 'bt@0@dm!n', '2020-04-03 06:27:19', 'Chemistry sometimes is called the \"central science\" because it connects other sciences to each other, such as biology, physics, geology, and environmental science. Here are some of the best reasons to study chemistry. Chemistry helps you to understand the world around you. The Importance of Chemistry in Life and Society. Chemistry as a subject has significant importance in our daily lives and society in general. Everything on the earth is made of chemicals. It also describes various chemical elements present in the environment, their reactions, and effects on the environment.', 'allbranches'),
('M2', 'bt@0@dm!n', '2020-04-03 06:27:36', 'Mathematics is a branch of science, which deals with numbers and their operations. It involves\r\ncalculation, computation, solving of problems, etc.', 'allbranches'),
('Data Structures', 'bt@0@dm!n', '2020-04-03 06:27:52', 'It is not a programming language to learn but it helps to us to organize data in different formats, it explains us in what format it is in such as inserting and deleting elements in stacks, queues and it explains about the linked list, graphs, and trees.', 'allbranches'),
('Digital Logic Design', 'bt@0@dm!n', '2020-04-03 06:28:07', 'This subject gives us a piece of brief information about how the logic works and how the system converts user understandable language to machine understandable language in the form of binary numbers like number conversions. digital logic design is used to represent signals and sequence by using decoders, encoders and so on.', 'cse'),
('MEFA', 'bt@0@dm!n', '2020-04-03 06:28:22', 'Managerial economics helps managers to decide on the planning and control of the benefits. Managerial Economics is synchronized between the planning and control of any institution or firm and hence its importance increases. Thus, It plays a huge role in business decisions.', 'allbranches'),
('DBMS', 'bt@0@dm!n', '2020-04-03 06:28:35', 'Database management systems are therefore crucial and important links in the creation as well as management of data. They are needed for effective running and management of data. It also helps companies to transfer the said data through the entire systems. Purpose of Database Management Systems. Organizations use large amounts of data. A database management system (DBMS) is a software tool that makes it possible to organize data in a database. The standard acronym for database management system is DBMS, so you will often see this instead of the full name.', 'cse'),
('BEE', 'bt@0@dm!n', '2020-04-03 06:29:42', 'Electronic communications engineers engage in research, design, development, and testing of the electronic equipment used in various communications systems. It is due to electrical engineers that we enjoy such modern communication devices as cellular telephones, radios, and television. The electrical and electronics engineering students learn the basics of the electrical and electronic circuits. They learn a number of things about the power generation and distribution of electricity. They also learn about the various electronic devices and how they are being manufactured', 'cse'),
('Java', 'bt@0@dm!n', '2020-04-03 06:29:59', ' Firstly as a computer science student learning a programming language is very much crucial.Java is a popular programming language used to create web applications and platforms which is designed in the flow of c and c++ languages, but it is simpler to use than c++. It is purely based on the object-oriented programming model. Most important java is platform independent. It is used to develop all kinds of applications and to develop all various mobiles, desktop and web applications. Nowadays for Android smartphone applications as it is a programming language. It was designed for users flexibility and to write code easily regardless of architecture or platform. The main advantage of Java language when compared to c, c++ languages is that java is very secured language and it may run on a single computer or be distributed among servers and clients in a network.', 'cse'),
('FLAT', 'bt@0@dm!n', '2020-04-03 06:30:13', 'The formal languages and automata theory belongs to computer science and mathematics. This subject is used to design abstract models for real-time problems. In this language there are different techniques are used to solve many theory-based problems using mathematical computations. The main aspect of this subject is to construct the syntax of programming languages. In mathematics, computer science normally a formal language consists of words whose letters are taken from an alphabet and are well-formed according to a specific set of rules.The language we consider for our discussion is an abstraction of normal languages. Relationship between grammar and language that is grammar is a set of production rules which are used to generate strings of a language. ', 'cse'),
('IT workshop', 'bt@0@dm!n', '2020-04-03 06:30:29', 'The workshop is the core of learning about different Materials, equipment, tools and manufacturing practices that are observed in different manufacturing functions and operations. The workshop is also of prime importance when you want to gather practical knowledge. Information technology gives you more knowledge about technologies and how to use it', 'allbranches'),
('computer organization', 'bt@0@dm!n', '2020-04-03 06:30:44', 'In computer engineering, computer organization is the set of rules and methods that describe the functionality and implementation of computer systems. Computer organization plays a key role, especially for computer science students. It is the study of internal working, structuring, and implementation of computer science. Computer design as an application of digital logic design procedures. It is concerned with the way the hardware components operate and the way they are connected together. Basically, the computer is mainly used for storing purpose and for performing different operations. For storing it requires some address memory that particular address is read here in this subject.', 'cse'),
('Software engineering ', 'bt@0@dm!n', '2020-04-03 06:31:00', 'Software engineering is the process of analyzing user needs and designing, constructing, and testing end-user applications that will satisfy these needs through the use of software programming languages. It is the application of engineering principles to software development. The need for software engineering arises because of the higher rate of change in user requirements and environment on which the software is working. Quality Management. Better process of software development provides a better and quality software product.', 'cse'),
('MPI', 'bt@0@dm!n', '2020-04-03 06:31:17', 'In this, we get a brief idea about the overview of 8085 architecture & pin diagram and also an overview of the 8086 architecture & pin diagram. Instructions of 8086 and know more about interrupts of 8086.this subject is to understand the working of processors and controllers, the architecture of 8085 microprocessor, the different addressing modes of 8085, Implement the middle-level programming and interfacing concepts in 8051', 'allbranches'),
('Probability & statistics', 'bt@0@dm!n', '2020-04-03 06:31:32', 'The most important part of programming is its use in problem-solving in programming languages. The main use of probability in our life is to measure the success or the fail of something. Also to measure the risk of many dangerous situations. Probability is also used to solve the true premises. Statistics is important for all branches of science, because it is incredibly helpful in decision making and testing the accuracy of the decisions at the end. In computer science and machine learning, the efficiency of algorithms can be significantly increased by using statistics. ... Computer science is deterministic', 'allbranches'),
('operating system', 'bt@0@dm!n', '2020-04-03 06:32:30', 'An operating system is system software that manages computer hardware and software resources and provides common services for the computer program. All computer programs, excluding firmware, require an operating system to function. For every computer, there should be a software called an operating system. It is the most important software that runs the computer. It manages the computers memory and processors, as well as all of its software and hardware. It also allows you to communicate with the computer without knowing how to speak the computers language. It helps the computer students very well.', 'cse'),
('Computer networking', 'bt@0@dm!n', '2020-04-03 06:32:49', 'Computer networking is the study of how computers can be linked to share data. The network is most important to run and work on the computer. A computer without a network has little use in daily life. A solid math background is valuable, like all the computer science and engineering fields. Good programming skills are also very much important in computer fields. There are more internship opportunities for computer students on networking range from simple network testing and troubleshooting to backend researching.', 'cse'),
('Object-oriented analysis and design ', 'bt@0@dm!n', '2020-04-03 06:33:08', 'Object-oriented analysis and design (OOAD) is a popular technical approach for analyzing and designing an application, system, or business by applying object-oriented programming, as well as using visual modeling throughout the development life cycles to foster better stakeholder communication and product quality.', 'cse'),
('software testing', 'bt@0@dm!n', '2020-04-03 06:33:23', 'A software testing engineer plays a crucial role in application development...since software testing is critical to the usability and quality of the final product, testers are bought in the design and planning stage and they may continue to provide support after the product is released. After writing every code that should be tested for that purpose software tester is needed. By this communication skills, mathematical skills and software application skills will be developed ', 'cse'),
('Principles of programming language', 'bt@0@dm!n', '2020-04-03 06:34:50', 'It is natural for computer science students to wonder how they will benefit from this subject.The main reason behind the study of the principle of the programming language is to provide good knowledge about the fundamentals to design, implementation, and application of the programming languages.Programming languages are vital elements in todays software development. Many programmers use multiple languages to develop softwares, however many programmers prefer to use only one or two languages for developing software. The programming language is the proper and easy way of writing complex programs which enables us to write efficient programs and develop software, applications and games, etc. For this purpose programming language is very much important', 'cse'),
('Introduction to Big Data', 'bt@0@dm!n', '2020-04-03 06:36:21', 'Due to the advancement in sciences, engineering and technology in recent years, the human endeavors and the social and economic activities have been generating a tremendous amount of data which is referred to as big data. Sources of big data include online transactions, scientific events, web posts, search engine, health records data, and mobile phone applications.', 'cse'),
('R Programming', 'bt@0@dm!n', '2020-04-03 06:36:38', 'R performs a wide variety of functions, such as data manipulation, statistical modeling, and graphics. The one really big advantage of R, however, is its extensibility. Developers can easily write their own software and distribute it in the form of add-on packages.R are a programming language and free software environment for statistical computing and graphics that is supported by the R Foundation for Statistical Computing. The R programming language is widely used among statisticians and data miners for developing statistical software and data analysis.', 'cse'),
('Introduction to Operation Management', 'bt@0@dm!n', '2020-04-03 06:37:02', 'Operations management is the administration of business practices to create the highest level of efficiency possible within an organization. It is concerned with converting materials and labor into goods and services as efficiently as possible to maximize the profit of an organization. Operation management is a process that involves planning, organizing, managing, controlling and supervising the production and manufacturing processes.', 'cse'),
('Design patterns', 'bt@0@dm!n', '2020-04-03 06:37:16', 'In software engineering, a design pattern is a general repeatable solution to a commonly occurring problem in software design. A design pattern is not a finished design that can be transformed directly into code. It is a description or template for how to solve a problem that can be used in many different situations.', 'cse'),
('Compiler design', 'bt@0@dm!n', '2020-04-03 06:37:33', 'A compiler is a computer program (or set of programs) that transforms source code written in a programming language (the source language) into another computer language (the target language, often having a binary form known as object code). The most common reason for converting source code is to create an A compiler is a computer program that transforms computer code written in one programming language (the source language) into another programming language (the target language). Compilers are a type of translator that support digital devices, primarily computers.', 'cse'),
('Data warehousing & mining', 'bt@0@dm!n', '2020-04-03 06:38:16', 'Data mining helps analysts to recognize significant facts, relationships, trends, patterns and anomalies which might go unnoticed otherwise.In business, data mining is useful for discovering patterns and relationships in data to help make better decisions.Data mining is the process of discovering patterns in large data sets involving methods at the intersection of machine learning, statistics, and database systems, Data mining is the analysis step of the \"knowledge discovery in databases\" process.', 'cse'),
('Design & analysis of algorithm', 'bt@0@dm!n', '2020-04-03 06:38:32', 'An algorithm is important in optimizing a computer program according to the available resources. Ultimately when anyone decides to solve a problem through better algorithms then searching for the best combination of program speed and the least amount of memory consumption is desired. An algorithm is a procedure or formula for solving a problem. Algorithms are extremely important while solving any type of computer science problems. Ideally, when faced with a problem, the first thing we should do is draw a flowchart of how we can solve the problem. The algorithm is programming language independent.', 'cse'),
('Artificial Intelligence', 'bt@0@dm!n', '2020-04-03 06:39:39', 'Artificial Intelligence is the machines which are designed and programmed in such a manner that they and think and act like a human. Artificial Intelligence becomes an important part of our daily life. Our life is changed by AI because this technology is used in a wide area of day to day services. Artificial intelligence (AI) is an area of computer science that emphasizes the creation of intelligent machines that work and react like humans. Some of the activities computers with artificial intelligence are designed for include: Speech recognition, learning.', 'cse'),
('Linux Environment System', 'bt@0@dm!n', '2020-04-03 06:41:17', 'Linux is a Unix-like, open source and community-developed operating system for computers, servers, mainframes, mobile devices, and embedded devices. It is supported on almost every major computer platform including x86, ARM and SPARC, making it one of the most widely supported operating systems. Basic Features. Following are some of the important features of the Linux Operating System. Portable – Portability means software can works on different types of hardware in the same way. Linux kernel and application programs support their installation on any kind of hardware platform.', 'cse'),
('System Application and Prodcut', 'bt@0@dm!n', '2020-04-03 06:42:13', 'SAP is an ERP (Enterprise Resource Planning) software by the same name as the company. SAP is a German acronym which is spelled in English as “Systems, Applications, and Products in data processing”. The best place to study SAP is through its certification programs. Why SAP Skills are so Important. ... In the field of enterprise software, SAP is the worlds market leader. More than 300.000 customers worldwide make use of SAP products in order to execute their business processes (e.g., controlling, sales, production, logistics, human resources, marketing, etc.)', 'cse'),
('Information security', 'bt@0@dm!n', '2020-04-03 06:43:08', 'Information security is importance in any organizations such as business, records keeping, financial and so on. This information security will help the organizations to fulfill the needs of the customers in managing their personal information, data, and security information. There are a few challenges faced by the organizations in managing the information so that it would fall in hand of unauthorized person or hackers. Besides, an effective information security management system can reduce the risk of crisis in the organizations. In order to know more about the importance of information security, organizations need to overcome the challenges first. Other than that, all organizations must have their policies to secure their information so that the information can be kept safely', 'cse'),
('Management science', 'bt@0@dm!n', '2020-04-03 06:43:22', 'Definition of management science. management science. The study of statistical methods, such as linear programming and simulation, in order to analyze and solve organizational problems. Same as operations research.The Management Science and Engineering online program is directed toward integrating scientific methods with the functional aspects of organizations by investigating the application of quantitative methodology and systems analysis in the context of decision making, risk analysis, economics and cost analysis, production', 'cse'),
('Grid & cloud computing', 'bt@0@dm!n', '2020-04-03 06:44:13', 'Difference between Grid Computing and Cloud Computing. ... While grid computing involves virtualizing computing resources to store massive amounts of data, whereas cloud computing is where an application doesnot access resources directly, rather it accesses them through a service over the internet.Grid Computing. Grid Computing is a type of distributed computing that combines the resources of interconnected groups of several independent computers that communicate through the use of a network in a way that makes them look and act like a single computing entity.', 'cse'),
('Mobile application development', 'bt@0@dm!n', '2020-04-03 06:44:44', 'Mobile application development is the set of processes and procedures involved in writing software for small, wireless computing devices. Like Web application development, mobile application development has its roots in more traditional software development. One critical difference, however, is that mobile apps are often written specifically to take advantage of the unique features a particular mobile device offers. For instance, a gaming app might be written to take advantage of the iPhones accelerometer or a mobile health app might be written to take advantage of a smartwatchs temperature sensor.', 'cse'),
('Network Analysis', 'bt@0@dm!n', '2020-04-07 04:17:20', 'It gives a basic idea about the fundamental electric circuits. By various methods and techniques which we deals in Network analysis are used to analysis the circuits.', 'ece'),
('Electronic devices and circuit', 'bt@0@dm!n', '2020-04-07 04:18:24', ' Electronic devices and circuits will make us understand about the semiconductor devices , properties ,basic elements of a circuit and analysation of FET , BJT ,transistors and diode.', 'cse'),
('Switching theory and logical design', 'bt@0@dm!n', '2020-04-07 04:19:03', 'STLD is a fundamental concepts of designing a digital system , it will give a brief idea about conversion of number system , complements , boolean algebra , K-maps .....etc., which are the bases of a digital analysation.', 'ece'),
('Signals & systems', 'bt@0@dm!n', '2020-04-07 04:19:41', ' In order to analyse any system , first we must have a basic idea/ information about the mathematical expressions of the elementary signals and conversion from time domain to frequency domain  this subject provides a basic information about signals , and systems.', 'ece'),
('Probability theory & stochastic processes', 'bt@0@dm!n', '2020-04-07 04:20:10', 'Probability theory and stochastic processes deals with probability which means chance and random variables ,correlations , noises ...etc., which are used to remove the Hum signals in communication system.', 'ece'),
('electrical theory', 'bt@0@dm!n', '2020-04-07 04:20:36', 'Electrical technology is used to analyse the performance of the generator , motors , transformers ....etc', 'ece'),
('M4', 'bt@0@dm!n', '2020-04-07 04:21:01', 'To help the students in getting a thorough understanding of the fundamentals of probability and usage of  statistical techniques like testing of hypothesis, Statistical Quality Control and Queuing theory', 'ece'),
('Electromagnetic theory & transmission lines', 'bt@0@dm!n', '2020-04-07 04:21:33', 'Electromagnetic theory and transmission lines will give the brief idea about the electromagnetic radiation which is now used in communications.By this technical skills of the ELECTROMAGNETIC THEORY & TRANSMISSION LINES , we may design the communication systems effectively without  any noise (or) Hum', 'ece'),
('Control system engineering', 'bt@0@dm!n', '2020-04-07 04:22:00', 'All the electronic devices & electrical devices which are trending almost are connected as feedback connection.The stability of a system can be analysed and what are the errors and how to eradicate errors & frequency domain specification can be analysed with the help of control system.', 'ece'),
('Electronic circuit & analysis', 'bt@0@dm!n', '2020-04-07 04:22:27', 'In Electronic circuit analysis , we analyse the basic characteistics of a signal i.e., the frequency response ,gain , voltage gains and other characteristics of the output (or) response. We can be able to design the multistage circuits , amplifier and oscillator just with the knowledge of ECA', 'ece'),
('Analog communication system', 'bt@0@dm!n', '2020-04-07 04:22:49', 'Basic fundamental concepts of analog communications like Modulation sampling and other techniques & working of transmitter and receivers and knowledge to avoid noise in analog communication can be studied here.', 'ece'),
('Digital system design', 'bt@0@dm!n', '2020-04-07 04:23:52', 'Basics about CMOS logic which is the simple thing in VLSI designing and the VHDL programs about any digital logic circuits. By this knowledge which we acquired , we can write a program for any electronic device based on its inputs, performance and logic gates used. This is mainly used while designing . Before designing any electronic device , we can test its working. Whether it works (or) not by this VHDL programs. This may reduce the loss of investment in designing.', 'ece'),
('Anteenas & wave propagation', 'bt@0@dm!n', '2020-04-07 04:24:37', 'What are the antennas used in effective communication & calculation of vector potentials of electromagnetic waves & by this basic idea of the antennas , we may design better transmitter and receiver , communication system.', 'ece'),
('Linear integrated circuits & application', 'bt@0@dm!n', '2020-04-07 04:25:06', 'Basics about Integrated circuits and characteristics , and applications and the importance of operational amplifier can be studied in LICA, LICA will help us in chip designing.', 'ece'),
('Digital communication system', 'bt@0@dm!n', '2020-04-07 04:25:28', 'The concepts like sampling , aliasing effect and modulation techniques can be easily understood by us which help in transmitting the information without any error. The information flow in communication system can be easily analysed so that we are capable of designing an Digital system.\r\n', 'ece'),
('Micro processor and Micro controller', 'bt@0@dm!n', '2020-04-07 04:25:56', 'MP & MC make us understand the working of processors and controllers , which are being used for working of mobile , computer and other devices The MP MC will give a detail idea about the processors and controllers.\r\n', 'ece'),
('Electronic measurement & instrumentation', 'bt@0@dm!n', '2020-04-07 04:26:30', 'The working of advanced instruments such as logic analyzers and the basic principles like voltage , current and so on.., can be studied completely in detail.', 'ece'),
('Digital signal processing', 'bt@0@dm!n', '2020-04-07 04:26:52', 'The digital signal process is used to design the filters and algorithms  which may improve performances of the system can be possible. This mainly used in satellite communication.', 'ece'),
('VLSI design', 'bt@0@dm!n', '2020-04-07 04:27:12', 'VLSI design gives the complete knowledge about the fabrication process of CMOS and we can be able to design the levels of design / Fabrication and layout designing and its specifications and designs rules of the VLSI and designing.\r\n', 'ece');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `whyweneedtostudy`
--
ALTER TABLE `whyweneedtostudy`
  ADD PRIMARY KEY (`dateofupload`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
